# Generated by Django 4.2.2 on 2023-06-26 23:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='details',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='employee',
            name='job_title',
            field=models.CharField(default='', max_length=100),
        ),
    ]
